### ISSUE TITLE
available times placement

### ISSUE THREAD

**Issue by kapnkush** [CraigT543/EasyBlue#11]
Hello,  having trouble resolving an issue with the way the available appointments are displaying..
![issue](https://cloud.githubusercontent.com/assets/19352169/25440052/d553f18c-2a63-11e7-84b4-6d7859c309fa.png)

**Comment by bullmoose20** [comment]
Should be resolved in the latest code that I committed about 5 days ago.

**Comment by kapnkush** [comment]
Thanks for the response. I had a copy from about 2 weeks ago.
