### ISSUE TITLE
5-day work week

### ISSUE THREAD

**Issue by nuddernuby** [CraigT543/EasyBlue#35]
Hi Craig,

Would you be able to advise how the calendar view could be set to show only 5 days - Monday to Friday?

Thank you

**Comment by mickeyf** [comment]
Not sure how Craig is handling this yet, but...

edit the .js file at:     \assets\ext\jquery-fullcalendar\fullcalendar.js
line 11522 (or thereabout) set -  weekends: false,

that should do it.

**Comment by nuddernuby** [comment]
Thanks, Mickey, this works fine. 
Solved.
